#ifndef _KAPI_X86_CPUID_H
#define _KAPI_X86_CPUID_H

/* 
    eax = 0x80000001
*/
#define CPUID_LAHF_SAHF_AVAIL_IN_64 1<<0
#define CPUID_LZCNT_AVAIL   1<<5
#define CPUID_PREFETCHW_AVAIL    1<<8
#define CPUID_SYSCALL_SYSRET_AVAIL   1<<11
#define CPUID_EXECUTE_DISABLE_BIT_AVAIL 1<<20
#define CPUID_1GIB_PAGE_AVAIL   1<<26
#define CPUID_RDTSCP_IA32_TSC_AUX_AVAIL    1<<27
#define CPUID_64ARCH_AVAIL  1<<29

#endif